### ISSUE TITLE
Edit change event not triggering on character deletion/backspace

### ISSUE THREAD

**Issue by MRB60** [JiHong88/SunEditor#173]
When a character is deleted, no change is detected and the save button remains disabled. Character insert works fine.

**Comment by JiHong88** [comment]
Hi, @MRB60 

Fixed in [v2.23.4](https://github.com/JiHong88/SunEditor/releases/tag/2.23.4)

Thank you!!

**Comment by quanle1994** [comment]
Hello. Thank you so much for the cool component.

I think the issue still happens in Chrome and Firefox.

Also, I notice there's a delay in the onChange callback. Is there a way to reduce this lag or remove it altogether?

Regards.

**Comment by MRB60** [comment]
Backspace onChange event works for me both in Chrome (v79.0.39) and Firefox on Linux with Suneditor v2.23.4. There is a delay (to reduce events?) though but for me not a problem.

**Comment by quanle1994** [comment]
I see. Could you try again when press and hold the backspace? So instead of deleting one character at a time, delete the whole chunk by holding down the backspace key.

**Comment by MRB60** [comment]
You are right - holding down backspace so it repeats does not seem trigger onChange.
