### ISSUE TITLE
Audio is not working

### ISSUE THREAD

**Issue by roker15** [JiHong88/SunEditor#936]
I clicked on audio button, provided URL link to a audio file 
https://file-examples-com.github.io/uploads/2017/11/file_example_MP3_2MG.mp3

After this everything is saved in database.
But when i click on audio widget it is not clickable and i can not play audio.

Do i need to import any extra plugin or file for playing audio? I am using latest chrome

**Comment by JiHong88** [comment]
Does it mean that "preview" doesn't work?
You cannot play video or audio while editing.
This will be improved in version 3.0.0.

**Comment by roker15** [comment]
> Does it mean that "preview" doesn't work? You cannot play video or audio while editing. This will be improved in version 3.0.0.

1. I am using editor both for editing and viewing (by disabling toolbar in view mode). but audio is not playable in both mode. Is there a way/mode to make audio playable something like "read mode"?
2. Also recently i updated to latest version but my **custom** paragraph styles stopped working. earlier it was working. I am using suneditor react also along with suneditor core.
3. When version 3.0.0 coming?
4. You were supposed to fix paste issue in earlier version.
5. please consider to add keyboard shortcut to katex , saving some standards maths equation, voice typing , and Organic chemistry support. in version 3. 0.0.

lastly -- your editor is best in market i have tried all. Great work.

**Comment by JiHong88** [comment]
1. I'll fix it so that it can be played back in read mode.
2. Show me the code for the custom paragraph style that stopped working.
3. The 3.0.0 version is in progress with the revision of legacy code, so it will take some time.
 We can't give you a specific date yet.
4. What are the paste issues?
5. I will consider it.
6. Probably not difficult to migrate.

**Comment by roker15** [comment]
> 1. I'll fix it so that it can be played back in read mode.
> 2. Show me the code for the custom paragraph style that stopped working.
> 3. The 3.0.0 version is in progress with the revision of legacy code, so it will take some time.
>    We can't give you a specific date yet.
> 4. What are the paste issues?
> 5. I will consider it.
> 6. Probably not difficult to migrate.

Regarding Point 2 here is the code --
```
<EditorStyle title={editorMode === "READ" ? "READ" : "EDIT"}>
        <SunEditor
          getSunEditorInstance={getSunEditorInstance}
          setDefaultStyle="font-family: arial; font-size: 14px;"
          hideToolbar={editorMode === "READ" ? true : false}
          defaultValue={language === "ENGLISH" ? article.article_english : article.article_hindi}
          // key={postId}

          onChange={handleOnChange}
          readOnly={editorMode === "READ" ? true : false}
          autoFocus={false}
          // disable={editorMode === "READ" ? true : false}
          setOptions={{
            placeholder: "**** Start Writing your notes here, we will save it automatically!!!",
            mode: "classic",
            katex: katex,
            colorList: colors ,
            paragraphStyles: [
              "spaced",
              "neon",
              {
                name: "Box",
                class: "__se__customClass1",
              },
              {
                name: "ph2",
                class: "seCustomClass2",
              },
            ],
            textStyles: [
              "shadow",
              "code",
              "translucent",

              {
                name: "Highlighter 1",
                style:
                  "background-color:#FFFF88;padding: 1px;",
                tag: "span",
              },
              {
                name: "Highlighter 2",
                style:
                  "background-color:#CDEB8B;padding: 1px;",
                tag: "span",
              },
              {
                name: "Highlighter 3",
                style:
                  "background-color:#E1D5E7;padding: 1px;",
                tag: "span",
              },
              {
                name: "Highlighter 4",
                style:
                  "background-color:#E1D5E7;padding: 1px;padding-left: 1px",
                tag: "p",
              },
            ],
            height: "100%",
            resizingBar: false,
            buttonList: sunEditorButtonList,
            formats: ["p", "div", "h1", "h2", "h3"],
            font: sunEditorfontList,
            fontSize: [12, 14, 16, 20],
            imageFileInput: false, //this disable image as file, only from url allowed
            imageSizeOnlyPercentage: false,
            // imageUrlInput: true,
            // imageGalleryUrl: "www.qlook.com",
          }}
        />
      </EditorStyle>
```
Above code is react code and `</EditorStyle> `is a wrapper for styling
Here is `EditorStyle `code
```
const EditorStyle = styled.div`
  .sun-editor {
    /* margin-top: -18px !important; */
    /* border: 1px solid blue; */
    border: ${(props) => (props.title === "READ" ? "none" : undefined)};
    /* border: "none"; */
  }
  .__se__customClass1 {
    /* background: #7e7575;
    padding: 5px;
    list-style-position: inside;
    font-weight: 500;
    color: #464242; */

    background-color: #6e3c3c;
    padding: 5px;
    color: #464242;
    list-style-position: inside;
  }
  .__se__customClass2 {
    background-color: #f1e0e0;
    padding: 5px;
    list-style-position: inside;
    font-weight: 500;
    color: #464242;
    text-shadow: 2px 2px 5px green;
  }
 
`;
```

**Comment by roker15** [comment]
> 1. I'll fix it so that it can be played back in read mode.
> 2. Show me the code for the custom paragraph style that stopped working.
> 3. The 3.0.0 version is in progress with the revision of legacy code, so it will take some time.
>    We can't give you a specific date yet.
> 4. What are the paste issues?
> 5. I will consider it.
> 6. Probably not difficult to migrate.

Paste issue is the bug when i paste some text it paste so many break lines automatically. and looks like there are lots of blank space before and after text.

**Comment by roker15** [comment]
> > Paste issue is the bug when i paste some text it paste so many break lines automatically. and looks like there are lots of blank space before and after text.
> 
> Any examples?
https://github.com/JiHong88/SunEditor/issues/922

**Comment by JiHong88** [comment]
> 1. I'll fix it so that it can be played back in read mode.
> 2. Paste issue 

Only two issues have been resolved.
Please register again for other issues.
I will notify you after the version update.

**Comment by JiHong88** [comment]
The [2.43.0](https://github.com/JiHong88/SunEditor/releases/tag/2.43.0) version has been updated.
If this issue has not been resolved, please reopen this issue.
Thank you.

**Comment by roker15** [comment]
> The [2.43.0](https://github.com/JiHong88/SunEditor/releases/tag/2.43.0) version has been updated. If this issue has not been resolved, please reopen this issue. Thank you.

Audio is still not playble in readOnly mode. Play button is not clickable in read only mode. I am using react.
